### PR TITLE
Add 221.* IDE compatibility

### PR DESCRIPTION
**Pull request by bc-lee**
I didn't update any other dependencies, and I just modified this as shown here and tried to build. And I've been using this on CLion 2022.1 for a few days.
So far, it works as expected.

### CODE REVIEW

**Comment by brunowonka** [comment]
Thanks for the PR. I haven't been able to put time on this lately, especially because I've stopped using IntelliJ IDEs myself for my day to day work. I'll try my best to rev a new release with this this week.

**Comment by bc-lee** [comment]
Oh I see. I'm thinking about creating a fork and maintaining it.

By the way, can you tell me which IDE you are currently using? VS Code?

**Comment by tamird** [comment]
@brunowonka you could also give @bc-lee the commit bit on this repo, though I'm not sure what the Google policy on this is.

**Comment by brunowonka** [comment]
Yeah I'm looking into the policy and reaching out to the powers that be, I'll keep this updated.

**Comment by brunowonka** [comment]
Okay looks like it's fine for us to keep this repo. @bc-lee I think the biggest thing we want here is for you to be able to publish updates to the plugin. We should try it out with this release. Do you have a JB marketplace account so I can give you permissions on the plugin?
If you want to discuss this with larger bandwidth perhaps look for us in the [Fuchsia discord](https://discord.com/channels/835268677472485376/940619305362530344) (I'm always hanging in the `#networking` channel, just gimme a shout)

**Comment by bc-lee** [comment]
If I get maintainer rights to this GitHub repository and I can upload the plugin to JB Marketplace, then everything will be OK, and I'll maintain this repository. My JB Marketplace account is here: https://plugins.jetbrains.com/author/0dfc1c7f-fffa-4dfc-bf4b-7bc8e5a55599

**Comment by bc-lee** [comment]
Thank you for allowing me to upload the plugin. Also, thanks for the original work.
After building the plugin locally, I successfully uploaded it to JB Marketplace.
Screen Shot 2022-05-12 at 7 13 53

**Pull request merged**
